# numpy practice sessin

In [1]:
# import this library in j.notebook
import numpy as np

# Creating an array using numpy

In [2]:
# 1-D array
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(price)

3

In [7]:
len(food)

3

In [8]:
price[0:]

array([5, 5, 5])

In [9]:
food[1]

'samosa'

In [10]:
price.mean()

5.0

# Methods of making an array
- zeros method
- ones method
- empty method
- range method
- with specific interval

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# empty function is float by default so we need to mention the type of data if we want it to be an integer or another form
np.empty([2,2],dtype=int)

array([[ 770768659, 2132664519],
       [-564870614,  968333279]])

In [14]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
#table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
# with specific line space
np.linspace(1,100,num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [20]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [21]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array functions

In [22]:
a=np.array([10,12,15,2,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   6. , 100. , 320. ,   0.5,  10.3])

In [23]:
a.sort()
a

array([  0.5,   2. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. , 320. ])

In [24]:
b=np.array([10.2, 3.4, 53.6, 91.2, 45.5])
b

array([10.2,  3.4, 53.6, 91.2, 45.5])

In [25]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. , 320. ,
        10.2,   3.4,  53.6,  91.2,  45.5])

In [26]:
c.sort()
c

array([  0.5,   2. ,   3.4,   6. ,  10. ,  10.2,  10.3,  12. ,  15. ,
        45.5,  53.6,  91.2, 100. , 320. ])

# 2-D arrays

In [27]:
a= np.array([[1,2], [5,4]])
a

array([[1, 2],
       [5, 4]])

In [28]:
b= np.array([[6,7],[7,8]])
b

array([[6, 7],
       [7, 8]])

In [29]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [30]:
np.concatenate((a,b),axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [31]:
a= np.array([[[0,1,2,3], 
                       [4,5,6,7]],
             
                       [[0,1,2,3],
                       [4,5,6,7]],
                       
                       [[0,1,2,3],
                       [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [32]:
#to find the number of dimenssions
a.ndim

3

In [33]:
b=np.array([[5,6,7],
          [8,9,10],
          [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [34]:
b.ndim

2

In [35]:
#no of elements
a.size

24

In [36]:
# shape
a.shape

(3, 2, 4)

In [37]:
a=np.arange(9)  #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
# reshape
a=a.reshape(3,3)  #3*3=9
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
np.reshape(a,newshape=(1, 9), order='c')  # c=column

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [40]:
# convert 1-D into 2-D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.shape

(9,)

In [42]:
#row wise 2d conversion
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
b.shape

(1, 9)

In [44]:
#column wise
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# slicing
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [47]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [48]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
a.sum()

45

In [50]:
a.mean()

5.0