In [4]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
len(a)

3

In [7]:
a[0]

5

In [8]:
a[0:]

array([5, 5, 5])

In [17]:
c=np.zeros(2)
c

array([0., 0.])

In [19]:
d=np.ones(3)
d

array([1., 1., 1.])

In [20]:
e=np.empty(3)
e

array([1., 1., 1.])

### 2-D array

In [10]:
# list of lists
b=np.array([[5,5,5], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
type(b)

numpy.ndarray

In [12]:
len(b)

3

In [13]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
np.empty([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### how to create an array with range of elements

In [21]:
f=np.arange(6)
f

array([0, 1, 2, 3, 4, 5])

In [23]:
# with specific range of elements
g=np.arange(2, 20)
g

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
# continue
h=np.arange(2, 20, 2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
#linearly spaced arrays
i=np.linspace(0,10,num=5)  #give use 5 nums
i

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
# specific data types in array
j= np.ones(5, dtype=np.int8)
j

array([1, 1, 1, 1, 1], dtype=int8)

In [28]:
k=np.ones(3, dtype=np.float64)
k

array([1., 1., 1.])

### making and reshaping a 3D array

In [32]:
l=np.arange(24).reshape(2, 3, 4)
l

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])